# Generated by Django 3.1.5 on 2021-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_lineitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderlineitem',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
