# Generated by Django 3.1.5 on 2021-02-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_oxxoorder_oxxoorderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxxoorder',
            name='original_bag',
            field=models.TextField(default=''),
        ),
    ]
