# Generated by Django 3.1.5 on 2021-02-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_oxxoorder_original_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oxxo',
            field=models.BooleanField(default=False),
        ),
    ]
