# Generated by Django 3.1.5 on 2021-02-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210219_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxxoorder',
            name='upgraded_order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oxxoorder', to='checkout.order'),
        ),
    ]
